import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import Landing from "../app/components/landing";

// 119/#257. The landing is the public face: hero, one CTA swapped by sign-in
// state (decided 2026-08-25 in the prototype: signed out the form does not
// exist), the three principles, and the Art. 50 disclosure. Until #156 ships
// the demo replay, the signed-out CTA offers sign-in rather than promising a
// demo that does not exist.

const { availableMock, onAuthChangeMock, mountButtonMock } = vi.hoisted(() => ({
  availableMock: vi.fn(),
  onAuthChangeMock: vi.fn(),
  mountButtonMock: vi.fn(),
}));

vi.mock("../app/lib/auth", () => ({
  signInAvailable: availableMock,
  onAuthChange: onAuthChangeMock,
  mountGoogleButton: mountButtonMock,
}));

afterEach(() => {
  cleanup();
  vi.resetAllMocks();
});

/** Drives the auth subscription the component registers. */
function withSession(signedIn: boolean) {
  availableMock.mockReturnValue(true);
  mountButtonMock.mockResolvedValue(undefined);
  onAuthChangeMock.mockImplementation((listener: (v: boolean) => void) => {
    listener(signedIn);
    return () => {};
  });
}

describe("landing", () => {
  it("shows the hero and offers the demo when signed out", () => {
    // 061 restores the prototype's hero: the demo is the one runnable thing
    // for a visitor, so it is the primary — sign-in becomes the second line.
    withSession(false);
    render(<Landing />);

    expect(
      screen.getByRole("heading", { name: "A verdict — and how sure it is." }),
    ).toBeDefined();
    const demo = screen.getByRole("link", { name: "Run the demo test" });
    expect(demo.getAttribute("href")).toBe("/test?demo=save-half");
    expect(
      screen.getByRole("button", { name: /sign in to run your own/i }),
    ).toBeDefined();
    expect(
      screen.queryByRole("link", { name: "Run your own test" }),
    ).toBeNull();
  });

  it("offers the run itself when signed in", () => {
    withSession(true);
    render(<Landing />);

    const cta = screen.getByRole("link", { name: "Run your own test" });
    expect(cta.getAttribute("href")).toBe("/test");
    expect(screen.getByText("Three runs a day.")).toBeDefined();
    expect(
      screen.queryByRole("button", { name: "Sign in to run a test" }),
    ).toBeNull();
  });

  it("opens the sign-in sheet from the second line, with Google's button mounted", () => {
    withSession(false);
    render(<Landing />);

    fireEvent.click(
      screen.getByRole("button", { name: /sign in to run your own/i }),
    );

    expect(screen.getByRole("dialog", { name: "Sign in" })).toBeDefined();
    expect(mountButtonMock).toHaveBeenCalledTimes(1);

    fireEvent.click(screen.getByRole("button", { name: "Not now" }));
    expect(screen.queryByRole("dialog", { name: "Sign in" })).toBeNull();
  });

  it("carries the three principles and the disclosure", () => {
    withSession(false);
    render(<Landing />);

    for (const principle of [
      "Every vote is on the record",
      "Uncertainty stays attached",
      "You approve the panel",
    ]) {
      expect(screen.getByRole("heading", { name: principle })).toBeDefined();
    }
    expect(
      screen.getByText(
        "The panel is synthetic personas, not people, and every verdict on this site is generated by an AI system.",
      ),
    ).toBeDefined();
  });
});
