/** The Art. 50(1) disclosures (074/#164), and the demo's replay note.
 *
 *  Kept in one place because a redesign came within a build of deleting both
 *  (098/#207): inline copy is lost by omission, an import has to be deleted on
 *  purpose. Each belongs with the control that starts an exchange — beside the
 *  submit button, and in the analyst's header — never in a footer.
 */

/** For the form: submitting headlines to a synthetic panel is the interaction. */
export const AI_SYSTEM_DISCLOSURE =
  "PanelVerdict is an AI system: the panel is synthetic personas, and the verdict and analyst answers are AI-generated.";

/** For the analyst dock: chatting with it is a second, separate interaction. */
export const ANALYST_DISCLOSURE =
  "The analyst is an AI system, not a person. Answers come from this test's own numbers. Every panelist is synthetic.";

/** For the landing: what the whole site is, said before anything is clicked.
 *  Beside the hero's one control, per the same rule as the other two. */
export const LANDING_DISCLOSURE =
  "The panel is synthetic personas, not people, and every verdict on this site is generated by an AI system.";

/** For the demo replay: what a visitor is watching, said where it plays. Not
 *  an Art. 50 disclosure — the demo renders AI_SYSTEM_DISCLOSURE for that —
 *  but it lives here for the same reason the others do: inline copy is lost
 *  by omission, an import has to be deleted on purpose. The date is the
 *  run's own, so the sentence is finished beside the report. */
export const DEMO_REPLAY_NOTE =
  "nothing is spent when you watch it, and every vote and reason is that run's own.";
