#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=7

# Captured values live in .env.deploy (gitignored) — NEVER the local .env, whose
# POSTGRES_* point at the docker-compose database. The seed stage injects the
# captured values as environment overrides (env beats dotenv in pydantic-settings).
ENV_FILE=".env.deploy"

banner "PanelVerdict deploy — Vercel + Railway + Supabase + Actions (docs/deploy.md)"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checks the tools this wizard leans on. Nothing is created yet."
command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 \
  && say "✓ gh authenticated" || warn "gh missing/unauthenticated — stage 7 will be manual"
command -v uv >/dev/null 2>&1 && say "✓ uv present" || { warn "uv missing — stage 3 (seed) needs it"; }
[[ -f backend/pyproject.toml ]] || { warn "run this from the repo root"; exit 1; }
grep -q '^OPENROUTER_API_KEY=' .env 2>/dev/null \
  && say "✓ OPENROUTER_API_KEY found in local .env (the seed's embedding calls use it)" \
  || warn "no OPENROUTER_API_KEY in .env — the seed stage will fail without it"
note "Ship dark: nothing in this wizard announces a URL. Public is a later, separate act."
pause

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Supabase — create the project, capture the direct connection"
say "One project carries Postgres, pgvector and (later) auth."
open_url "https://supabase.com/dashboard/new"
step "Create a project — pick an EU region; set and REMEMBER the database password."
step "When it finishes provisioning: click 'Connect' (top bar)."
step "Choose 'Direct connection' — NOT a pooler. The host looks like db.<ref>.supabase.co."
note "Direct is IPv6-only; that is fine — Railway gets an IPv6 toggle in stage 4."
ask POSTGRES_HOST "Paste the direct host (db.<ref>.supabase.co):"
ask_secret POSTGRES_PASSWORD "Paste the database password:"
POSTGRES_USER="postgres"; POSTGRES_PORT="5432"; POSTGRES_DB="postgres"
write_env POSTGRES_HOST "$POSTGRES_HOST"
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env POSTGRES_USER "$POSTGRES_USER"
write_env POSTGRES_PORT "$POSTGRES_PORT"
write_env POSTGRES_DB "$POSTGRES_DB"

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Schema + seed, from this machine"
say "Applies schema.sql and seeds the persona pool into Supabase. The embedding"
say "calls are the one paid part; the dry run below prices the plan first."
note "Resumable by design: a re-run never re-pays for personas already seeded."
(cd backend && POSTGRES_HOST="$POSTGRES_HOST" POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
  POSTGRES_USER="$POSTGRES_USER" POSTGRES_PORT="$POSTGRES_PORT" POSTGRES_DB="$POSTGRES_DB" \
  uv run python -m app.seed --size full --dry-run) || warn "dry run failed — check the connection values"
if confirm "Run the real seed now (--size full)?"; then
  (cd backend && POSTGRES_HOST="$POSTGRES_HOST" POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
    POSTGRES_USER="$POSTGRES_USER" POSTGRES_PORT="$POSTGRES_PORT" POSTGRES_DB="$POSTGRES_DB" \
    uv run python -m app.seed --size full)
  say "✓ pool seeded"
else
  SKIPPED+=("the seed — run it later from backend/: uv run python -m app.seed --size full")
fi

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Railway — the always-on backend"
open_url "https://railway.app/new"
step "Deploy from GitHub repo → pick this repo."
step "Service Settings → Source → set Root Directory to: backend"
warn "BEFORE anything connects: Settings → Networking → 'Enable Outbound IPv6'."
note "Skipping that gives a bare ENETUNREACH against Supabase — the trap deploy-targets.md warns about."
step "Variables tab — add these, and SEAL the first three (⋮ menu → Seal):"
say "    OPENROUTER_API_KEY   (sealed — copy from your local .env)"
say "    POSTGRES_PASSWORD    (sealed)"
say "    POSTGRES_USER        (sealed)  = postgres"
say "    POSTGRES_HOST = $POSTGRES_HOST"
say "    POSTGRES_PORT = 5432    POSTGRES_DB = postgres"
say "    FRONTEND_ORIGIN — leave for stage 6.  PROFILE — leave unset (dev) while dark."
step "Settings → Networking → Public Networking → Generate Domain."
ask RAILWAY_URL "Paste the public URL (https://…up.railway.app, no trailing slash):"
RAILWAY_URL="${RAILWAY_URL%/}"
write_env RAILWAY_URL "$RAILWAY_URL"
say "Waiting for the deploy, then checking health (db must be 'up'):"
pause "Press Enter once the Railway deploy shows as successful"
if curl -fsS --max-time 30 "$RAILWAY_URL/health" | grep -q '"db":"up"'; then
  say "✓ backend is up and talking to Supabase over IPv6"
else
  warn "health check failed or db is down — check the IPv6 toggle and the POSTGRES_* variables"
  SKIPPED+=("backend health — re-check: curl $RAILWAY_URL/health")
fi

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Vercel — the frontend"
open_url "https://vercel.com/new"
step "Import this repo → set Root Directory to: frontend (framework auto-detects)."
step "Environment Variables → add NEXT_PUBLIC_API_URL = $RAILWAY_URL"
step "Deploy, then copy the production URL."
ask VERCEL_URL "Paste the Vercel URL (https://…vercel.app, no trailing slash):"
VERCEL_URL="${VERCEL_URL%/}"
write_env VERCEL_URL "$VERCEL_URL"
if curl -fsS --max-time 30 -o /dev/null -w '%{http_code}' "$VERCEL_URL" | grep -q '^200$'; then
  say "✓ frontend serves"
else
  warn "frontend did not answer 200 — check the Vercel build logs"
  SKIPPED+=("frontend check — curl -I $VERCEL_URL")
fi

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Cross-wire CORS"
step "Back in Railway → Variables → set FRONTEND_ORIGIN = $VERCEL_URL (it redeploys)."
pause "Press Enter once the redeploy is green"
if curl -fsS --max-time 30 -H "Origin: $VERCEL_URL" -D - -o /dev/null "$RAILWAY_URL/health" \
    | grep -qi '^access-control-allow-origin'; then
  say "✓ CORS answers for the Vercel origin"
else
  warn "no CORS header seen — check FRONTEND_ORIGIN matches the Vercel URL exactly"
  SKIPPED+=("CORS check — curl -H \"Origin: $VERCEL_URL\" -D - $RAILWAY_URL/health")
fi

# ── Stage 7 ────────────────────────────────────────────────────────────────
stage "GitHub — arm the keep-alive"
say "The daily /health ping keeps the Supabase free tier awake AND smoke-tests the stack."
set_var DEPLOY_HEALTH_URL "$RAILWAY_URL"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh workflow run keepalive.yml >/dev/null 2>&1 \
    && say "✓ keepalive dispatched — check: gh run list --workflow=keepalive.yml" \
    || warn "could not dispatch keepalive — run it from the Actions tab once"
fi
say ""
say "Final proof, when you're ready (a dev run costs ~half a cent):"
step "Open $VERCEL_URL — two headlines, Evaluate, then one analyst question."

finish
